-- Study Buddies — separate from /refer-earn referrals.
-- - buddy_invites: tokens generated by an inviter, shared via WhatsApp/etc.
-- - study_buddies: symmetric pair rows (both sides), one active pair per user enforced via unique on user_id where status='active'.
-- - accept_buddy_invite RPC: pairs both users, and if the acceptor has no referral attribution yet, also calls claim_referral_attribution with the inviter's hex ref code.

CREATE TABLE public.buddy_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  inviter_user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')),
  accepted_by_user_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  accepted_at timestamptz,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  CONSTRAINT buddy_invites_token_min CHECK (char_length(token) >= 8)
);

CREATE INDEX buddy_invites_inviter_status_idx ON public.buddy_invites (inviter_user_id, status);
CREATE INDEX buddy_invites_token_idx ON public.buddy_invites (token);

COMMENT ON TABLE public.buddy_invites IS 'Learning Buddy invite tokens shared via WhatsApp. Accepted via accept_buddy_invite RPC.';

CREATE TABLE public.study_buddies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  buddy_user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'ended')),
  created_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  CONSTRAINT study_buddies_no_self CHECK (user_id <> buddy_user_id),
  UNIQUE (user_id, buddy_user_id)
);

CREATE UNIQUE INDEX study_buddies_one_active_per_user
  ON public.study_buddies (user_id)
  WHERE status = 'active';

CREATE INDEX study_buddies_user_idx ON public.study_buddies (user_id, status);

COMMENT ON TABLE public.study_buddies IS 'Symmetric buddy pair rows (one row per side). At most one active buddy per user.';

ALTER TABLE public.buddy_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_buddies ENABLE ROW LEVEL SECURITY;

-- Inviter manages their own invites
CREATE POLICY buddy_invites_select_own ON public.buddy_invites
  FOR SELECT TO authenticated
  USING (auth.uid() = inviter_user_id);

CREATE POLICY buddy_invites_insert_own ON public.buddy_invites
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = inviter_user_id);

CREATE POLICY buddy_invites_update_own_revoke ON public.buddy_invites
  FOR UPDATE TO authenticated
  USING (auth.uid() = inviter_user_id)
  WITH CHECK (auth.uid() = inviter_user_id);

-- Both sides can read their pair rows (own row only, but two rows exist on accept)
CREATE POLICY study_buddies_select_own ON public.study_buddies
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

-- Writes (insert/end) only via service role inside RPCs
-- (no INSERT/UPDATE policy on study_buddies for authenticated)

-- ---------- accept_buddy_invite ----------
CREATE OR REPLACE FUNCTION public.accept_buddy_invite(p_token text, p_acceptor_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite RECORD;
  v_acceptor_onboarded boolean;
  v_pair_id uuid;
  v_referral_credited boolean := false;
  v_already_paired boolean := false;
  v_active_buddy_for_acceptor uuid;
  v_active_buddy_for_inviter uuid;
  v_ref_code text;
  v_referral_result jsonb;
BEGIN
  IF p_token IS NULL OR length(trim(p_token)) < 8 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_token');
  END IF;

  SELECT id, inviter_user_id, status, expires_at, accepted_by_user_id
    INTO v_invite
  FROM public.buddy_invites
  WHERE token = p_token
  LIMIT 1;

  IF v_invite.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_found');
  END IF;

  IF v_invite.status = 'accepted' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'already_accepted');
  END IF;

  IF v_invite.status = 'revoked' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'revoked');
  END IF;

  IF v_invite.expires_at <= now() THEN
    UPDATE public.buddy_invites SET status = 'expired' WHERE id = v_invite.id;
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;

  IF v_invite.inviter_user_id = p_acceptor_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'self_invite');
  END IF;

  SELECT onboarding_complete INTO v_acceptor_onboarded
  FROM public.profiles WHERE id = p_acceptor_id;
  IF v_acceptor_onboarded IS DISTINCT FROM true THEN
    RETURN jsonb_build_object('ok', false, 'error', 'onboarding_incomplete');
  END IF;

  -- If either side already has an active buddy, surface that without overwriting.
  SELECT buddy_user_id INTO v_active_buddy_for_acceptor
  FROM public.study_buddies
  WHERE user_id = p_acceptor_id AND status = 'active'
  LIMIT 1;

  SELECT buddy_user_id INTO v_active_buddy_for_inviter
  FROM public.study_buddies
  WHERE user_id = v_invite.inviter_user_id AND status = 'active'
  LIMIT 1;

  IF v_active_buddy_for_acceptor IS NOT NULL
     AND v_active_buddy_for_inviter IS NOT NULL
     AND v_active_buddy_for_acceptor = v_invite.inviter_user_id
     AND v_active_buddy_for_inviter = p_acceptor_id THEN
    v_already_paired := true;
  ELSIF v_active_buddy_for_acceptor IS NOT NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'acceptor_has_buddy');
  ELSIF v_active_buddy_for_inviter IS NOT NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'inviter_has_buddy');
  END IF;

  IF NOT v_already_paired THEN
    INSERT INTO public.study_buddies (user_id, buddy_user_id, status)
    VALUES (p_acceptor_id, v_invite.inviter_user_id, 'active')
    ON CONFLICT (user_id, buddy_user_id) DO UPDATE SET status = 'active', ended_at = NULL
    RETURNING id INTO v_pair_id;

    INSERT INTO public.study_buddies (user_id, buddy_user_id, status)
    VALUES (v_invite.inviter_user_id, p_acceptor_id, 'active')
    ON CONFLICT (user_id, buddy_user_id) DO UPDATE SET status = 'active', ended_at = NULL;
  END IF;

  UPDATE public.buddy_invites
     SET status = 'accepted',
         accepted_by_user_id = p_acceptor_id,
         accepted_at = now()
   WHERE id = v_invite.id AND status = 'pending';

  -- Dual outcome: if the acceptor has never been credited a referral, give referral RDM too.
  IF NOT EXISTS (SELECT 1 FROM public.referral_attributions WHERE referee_user_id = p_acceptor_id) THEN
    v_ref_code := upper(substr(replace(v_invite.inviter_user_id::text, '-', ''), 1, 7));
    BEGIN
      v_referral_result := public.claim_referral_attribution(v_ref_code, p_acceptor_id);
      IF (v_referral_result ->> 'ok')::boolean IS TRUE THEN
        v_referral_credited := true;
      END IF;
    EXCEPTION WHEN OTHERS THEN
      v_referral_credited := false;
    END;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'pairId', v_pair_id,
    'alreadyPaired', v_already_paired,
    'referralCredited', v_referral_credited
  );
END;
$$;

REVOKE ALL ON FUNCTION public.accept_buddy_invite(text, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.accept_buddy_invite(text, uuid) TO service_role;

COMMENT ON FUNCTION public.accept_buddy_invite IS 'Called with service_role only. Pairs both sides into study_buddies and (if first-time) also credits referral RDM via claim_referral_attribution.';

-- ---------- end_buddy_pair (Unbuddy) ----------
CREATE OR REPLACE FUNCTION public.end_buddy_pair(p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_buddy uuid;
BEGIN
  SELECT buddy_user_id INTO v_buddy
  FROM public.study_buddies
  WHERE user_id = p_user_id AND status = 'active'
  LIMIT 1;

  IF v_buddy IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'no_active_buddy');
  END IF;

  UPDATE public.study_buddies
     SET status = 'ended', ended_at = now()
   WHERE status = 'active'
     AND ((user_id = p_user_id AND buddy_user_id = v_buddy)
       OR (user_id = v_buddy AND buddy_user_id = p_user_id));

  RETURN jsonb_build_object('ok', true);
END;
$$;

REVOKE ALL ON FUNCTION public.end_buddy_pair(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.end_buddy_pair(uuid) TO service_role;

COMMENT ON FUNCTION public.end_buddy_pair IS 'Called with service_role. Ends both pair rows for the given user.';
