-- CBSE PUC foundational verbal (100), funbrain / verbal. Pack: cbse_verbal_puc100_foundational.
-- Idempotent: delete this pack in verbal, then insert.

BEGIN;

DELETE FROM public.play_questions
WHERE domain = 'funbrain'
  AND category = 'verbal'
  AND (content->>'pack') = 'cbse_verbal_puc100_foundational';

INSERT INTO public.play_questions (domain, category, content, options, correct_answer_index, explanation)
VALUES
  ('funbrain', 'verbal', '{"text": "What is a synonym for HUGE?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Narrow", "Tiny", "Brief", "Enormous"]'::jsonb, 3, 'Huge means very large; enormous is a close synonym (also: giant).'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for BRAVE?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Lazy", "Shy", "Courageous", "Cowardly"]'::jsonb, 2, 'Brave shows no fear; courageous / fearless match.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for START?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Finish", "Delay", "Stop", "Begin"]'::jsonb, 3, 'Start means to commence an action.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for CALM?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Loud", "Angry", "Peaceful", "Wild"]'::jsonb, 2, 'Calm means quiet and not agitated (also: peaceful).'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for RICH?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Poor", "Weak", "Hungry", "Wealthy"]'::jsonb, 3, 'Rich means having a lot of money or assets.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for HARD (difficult)?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Easy", "Simple", "Soft", "Difficult"]'::jsonb, 3, 'Hard often means not easy; solid is another sense.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for FAST?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Late", "Slow", "Quick", "Heavy"]'::jsonb, 2, 'Fast means high speed; quick / rapid match.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for BEAUTIFUL?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Ugly", "Dull", "Lovely", "Plain"]'::jsonb, 2, 'Beautiful means pleasing; pretty / lovely fit.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for HELP?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Assist", "Ignore", "Hinder", "Blame"]'::jsonb, 0, 'Help means aid someone; assist / aid match.'),
  ('funbrain', 'verbal', '{"text": "What is a synonym for HAPPY?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Angry", "Tired", "Joyful", "Sad"]'::jsonb, 2, 'Happy means pleased; joyful / glad match.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of ALWAYS?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Often", "Sometimes", "Usually", "Never"]'::jsonb, 3, 'Always = every time; never = not ever.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of ACCEPT?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Praise", "Keep", "Welcome", "Reject"]'::jsonb, 3, 'Accept = say yes; reject / refuse = say no.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of MODERN?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Young", "New", "Ancient", "Fresh"]'::jsonb, 2, 'Modern = current era; ancient / old are opposites.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of PUBLIC?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Free", "Loud", "Open", "Private"]'::jsonb, 3, 'Public = open to all; private = restricted.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of DEEP?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Shallow", "Wide", "Long", "High"]'::jsonb, 0, 'Deep goes far down; shallow is the opposite.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of SUCCESS?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Hope", "Failure", "Luck", "Win"]'::jsonb, 1, 'Success = reaching a goal; failure = not reaching it.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of CRUEL?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Strict", "Loud", "Bold", "Kind"]'::jsonb, 3, 'Cruel hurts on purpose; kind / gentle are opposites.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of IMPORT?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Buy", "Tax", "Export", "Sell"]'::jsonb, 2, 'Import brings goods in; export sends them out.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of LIGHT (not heavy)?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Soft", "Bright", "Dark", "Heavy"]'::jsonb, 3, 'Light weight vs heavy.'),
  ('funbrain', 'verbal', '{"text": "What is the antonym of HOT?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Cold", "Warm", "Cool", "Dry"]'::jsonb, 0, 'Hot vs cold temperature.'),
  ('funbrain', 'verbal', '{"text": "Fill in: The cat is hiding _____ the bed.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["under", "in", "at", "on"]'::jsonb, 0, 'Position directly below the bed.'),
  ('funbrain', 'verbal', '{"text": "Fill in: I will meet you _____ 5:00 PM.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["at", "by", "in", "on"]'::jsonb, 0, 'Use at for clock times.'),
  ('funbrain', 'verbal', '{"text": "Fill in: My birthday is _____ August.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["on", "to", "at", "in"]'::jsonb, 3, 'Use in for months.'),
  ('funbrain', 'verbal', '{"text": "Fill in: He is _____ honest boy.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["the", "one", "an", "a"]'::jsonb, 2, 'Honest begins with a vowel sound.'),
  ('funbrain', 'verbal', '{"text": "Fill in: She placed the book _____ the table.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["under", "on", "in", "at"]'::jsonb, 1, 'On the surface.'),
  ('funbrain', 'verbal', '{"text": "Fill in: They went to _____ sunniest beach in the state.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["a", "some", "the", "an"]'::jsonb, 2, 'The before superlatives.'),
  ('funbrain', 'verbal', '{"text": "Fill in: I go to school _____ bus.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["with", "in", "on", "by"]'::jsonb, 3, 'By + vehicle for transport mode.'),
  ('funbrain', 'verbal', '{"text": "Fill in: He has been sleeping _____ morning.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["for", "by", "since", "from"]'::jsonb, 2, 'Since + point in time with present perfect.'),
  ('funbrain', 'verbal', '{"text": "Fill in: Please give me _____ pen. (any pen)", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["some", "an", "a", "the"]'::jsonb, 2, 'Non-specific singular countable noun.'),
  ('funbrain', 'verbal', '{"text": "Fill in: She is walking _____ the park.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["through", "on", "at", "of"]'::jsonb, 0, 'Through / in / towards can fit; through is common for crossing the park.'),
  ('funbrain', 'verbal', '{"text": "Fill in: The sun _____ in the East.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["is rising", "rises", "rose", "rise"]'::jsonb, 1, 'Simple present for facts.'),
  ('funbrain', 'verbal', '{"text": "Fill in: They _____ playing football yesterday.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["were", "is", "are", "was"]'::jsonb, 0, 'Past continuous; plural they → were.'),
  ('funbrain', 'verbal', '{"text": "Fill in: She _____ not like ice cream.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["does", "do", "is", "has"]'::jsonb, 0, 'Third person singular negative uses does.'),
  ('funbrain', 'verbal', '{"text": "Fill in: I _____ my homework right now.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["do", "have done", "am doing", "did"]'::jsonb, 2, 'Present continuous for now.'),
  ('funbrain', 'verbal', '{"text": "Fill in: We _____ to the zoo tomorrow.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["go", "went", "will go", "goes"]'::jsonb, 2, 'Future: will go or are going; will go listed.'),
  ('funbrain', 'verbal', '{"text": "Fill in: He _____ a new car last week.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["buy", "buys", "has bought", "bought"]'::jsonb, 3, 'Past tense for last week.'),
  ('funbrain', 'verbal', '{"text": "Fill in: Dogs _____ a very good sense of smell.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["has", "have", "is having", "having"]'::jsonb, 1, 'Plural subject takes have.'),
  ('funbrain', 'verbal', '{"text": "Fill in: I _____ never seen a tiger in real life.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["have", "am", "has", "had"]'::jsonb, 0, 'Present perfect: have + past participle.'),
  ('funbrain', 'verbal', '{"text": "Fill in: Look! The bird _____ flying away.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["are", "is", "were", "was"]'::jsonb, 1, 'Singular present continuous.'),
  ('funbrain', 'verbal', '{"text": "Fill in: If it rains, I _____ stay home.", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["stays", "would", "stayed", "will"]'::jsonb, 3, 'First conditional: if + present, will + base.'),
  ('funbrain', 'verbal', '{"text": "What does \"piece of cake\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["A small snack", "A dessert order", "Something very easy", "A broken plate"]'::jsonb, 2, 'Informal: very easy to do.'),
  ('funbrain', 'verbal', '{"text": "What does \"raining cats and dogs\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Light drizzle", "Animals outside", "Raining very heavily", "Snowing hard"]'::jsonb, 2, 'Idiom for a downpour.'),
  ('funbrain', 'verbal', '{"text": "What does \"break a leg\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Leave quickly", "Get hurt", "Stop trying", "Good luck"]'::jsonb, 3, 'Said especially before a performance.'),
  ('funbrain', 'verbal', '{"text": "What does \"once in a blue moon\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Always", "Happens very rarely", "Every night", "Every month"]'::jsonb, 1, 'Very infrequent event.'),
  ('funbrain', 'verbal', '{"text": "What does \"apple of my eye\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["A fruit basket", "Someone cherished dearly", "A teacher", "An eye problem"]'::jsonb, 1, 'A person you love or value highly.'),
  ('funbrain', 'verbal', '{"text": "What does \"cost an arm and a leg\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["To be free", "To be very expensive", "To hurt physically", "To be cheap"]'::jsonb, 1, 'Hyperbole for high price.'),
  ('funbrain', 'verbal', '{"text": "What does \"under the weather\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["In the rain", "Very happy", "Outside", "Feeling sick"]'::jsonb, 3, 'Mildly unwell.'),
  ('funbrain', 'verbal', '{"text": "What does \"cry over spilled milk\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Clean the floor", "Buy more milk", "Worry about something past and unchangeable", "Cook carefully"]'::jsonb, 2, 'Don’t fuss over what cannot be undone.'),
  ('funbrain', 'verbal', '{"text": "What does \"hit the books\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Close the library", "To study hard", "Throw books", "Buy textbooks"]'::jsonb, 1, 'Serious studying before exams.'),
  ('funbrain', 'verbal', '{"text": "What does \"let the cat out of the bag\" mean?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Buy a pet", "Pack luggage", "Open a window", "To reveal a secret accidentally"]'::jsonb, 3, 'Spoil a surprise by telling.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"He go to school every day.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["No error", "Use \"going\"", "Use \"gone\"", "Use \"goes\" instead of \"go\""]'::jsonb, 3, 'He takes singular verb goes.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"She has two brother.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"brotheres\"", "No error", "Remove two", "Use \"brothers\""]'::jsonb, 3, 'Plural after two.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"I am read a book.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"reading\"", "No error", "Use \"readed\"", "Use \"reads\""]'::jsonb, 0, 'Present continuous: am + -ing.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"The children is playing outside.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"are\" instead of \"is\"", "Use \"be\"", "No error", "Use \"was\""]'::jsonb, 0, 'Children is plural.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"Me and John are friends.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Say \"John and me\" always", "Say \"John and I\"", "No error", "Say \"Me is\""]'::jsonb, 1, 'Subject pronoun I; name first is polite.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"He don''t like apples.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"doesn''t\"", "Use \"not\"", "Use \"don''t still\"", "No error"]'::jsonb, 0, 'He requires does not (doesn''t).'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"She sings very good.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"well\"", "Use \"gooder\"", "No error", "Use \"best\""]'::jsonb, 0, 'Adverb well modifies sings; good is adjective.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"I bought a apple.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"the\"", "No error", "Use \"some\"", "Use \"an\""]'::jsonb, 3, 'Vowel sound before apple.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"They was happy.\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["No error", "Use \"be\"", "Use \"is\"", "Use \"were\""]'::jsonb, 3, 'Plural they needs were.'),
  ('funbrain', 'verbal', '{"text": "Spot the error: \"Where is my shoes?\"", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Use \"is\" with pair", "Use \"are\"", "No error", "Use \"was\""]'::jsonb, 1, 'Shoes is plural.'),
  ('funbrain', 'verbal', '{"text": "A child whose parents have died is called a(n)...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Widow", "Bachelor", "Infant", "Orphan"]'::jsonb, 3, 'Standard term.'),
  ('funbrain', 'verbal', '{"text": "A person who eats no meat is a...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Farmer", "Chef", "Vegetarian", "Carnivore"]'::jsonb, 2, 'Plant-based diet (often with dairy/eggs).'),
  ('funbrain', 'verbal', '{"text": "Something that happens once every year is...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Monthly", "Daily", "Annual", "Hourly"]'::jsonb, 2, 'Yearly event.'),
  ('funbrain', 'verbal', '{"text": "A period of ten years is a...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Decade", "Century", "Fortnight", "Year"]'::jsonb, 0, 'Ten-year span.'),
  ('funbrain', 'verbal', '{"text": "A period of one hundred years is a...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Era", "Century", "Millennium", "Decade"]'::jsonb, 1, '100-year span.'),
  ('funbrain', 'verbal', '{"text": "A person who expects good outcomes is a(n)...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Realist", "Pessimist", "Optimist", "Critic"]'::jsonb, 2, 'Positive outlook.'),
  ('funbrain', 'verbal', '{"text": "A person who expects bad outcomes is a(n)...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Optimist", "Hero", "Pessimist", "Judge"]'::jsonb, 2, 'Opposite of optimist.'),
  ('funbrain', 'verbal', '{"text": "A book of word meanings is a...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Diary", "Atlas", "Novel", "Dictionary"]'::jsonb, 3, 'Alphabetical reference.'),
  ('funbrain', 'verbal', '{"text": "A person who treats sick animals is a...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Veterinarian", "Pilot", "Surgeon", "Dentist"]'::jsonb, 0, 'Animal doctor.'),
  ('funbrain', 'verbal', '{"text": "Safe to eat is...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Toxic", "Edible", "Stale", "Raw"]'::jsonb, 1, 'Fit for consumption.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for the rules of language?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Gramer", "Grammer", "Grammerr", "Grammar"]'::jsonb, 3, 'Grammar ends in -ar.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for the next day?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Tomorow", "Tommorow", "Tomorrow", "Tommorrow"]'::jsonb, 2, 'One m, two r’s.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “have faith”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Belive", "Beleeve", "Believe", "Beleive"]'::jsonb, 2, 'i before e here.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “get a letter”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Receeve", "Receive", "Receiv", "Recieve"]'::jsonb, 1, 'e before i after c.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “apart”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Seperete", "Separate", "Seperate", "Sepparate"]'::jsonb, 1, 'Par in the middle.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “clear and sure”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Definit", "Defenite", "Definate", "Definite"]'::jsonb, 3, 'Contains finite.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for a close companion?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Freind", "Frind", "Frend", "Friend"]'::jsonb, 3, 'Ends with end.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “in truth”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Turely", "Truely", "Trulyy", "Truly"]'::jsonb, 3, 'Drop e from true.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “up to the time”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Until", "Untilll", "Untill", "Untl"]'::jsonb, 0, 'One l.'),
  ('funbrain', 'verbal', '{"text": "Which spelling is correct for “strange”?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Weired", "Weird", "Werd", "Wierd"]'::jsonb, 1, 'Exception spelling ei.'),
  ('funbrain', 'verbal', '{"text": "Cat is to Kitten as Dog is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Calf", "Puppy", "Chick", "Cub"]'::jsonb, 1, 'Young of the species.'),
  ('funbrain', 'verbal', '{"text": "Day is to Night as Hot is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Cold", "Wet", "Warm", "Big"]'::jsonb, 0, 'Opposite pairs.'),
  ('funbrain', 'verbal', '{"text": "Bird is to Fly as Fish is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Swim", "Jump", "Walk", "Run"]'::jsonb, 0, 'Typical movement.'),
  ('funbrain', 'verbal', '{"text": "Pen is to Write as Knife is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Draw", "Cook", "Cut", "Eat"]'::jsonb, 2, 'Tool and main use.'),
  ('funbrain', 'verbal', '{"text": "Doctor is to Hospital as Teacher is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Studio", "Court", "School", "Office"]'::jsonb, 2, 'Job and workplace.'),
  ('funbrain', 'verbal', '{"text": "Eye is to See as Ear is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Smell", "Touch", "Hear", "Taste"]'::jsonb, 2, 'Sense organ and sense.'),
  ('funbrain', 'verbal', '{"text": "Apple is to Fruit as Carrot is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Meat", "Vegetable", "Grain", "Spice"]'::jsonb, 1, 'Food type category.'),
  ('funbrain', 'verbal', '{"text": "Car is to Road as Train is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Sky", "Tunnel", "Water", "Track"]'::jsonb, 3, 'Vehicle and surface it uses.'),
  ('funbrain', 'verbal', '{"text": "Book is to Read as Song is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Drive", "Paint", "Listen", "Write"]'::jsonb, 2, 'Object and typical experience (also sing).'),
  ('funbrain', 'verbal', '{"text": "Ice is to Cold as Fire is to...", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Hard", "Hot", "Dark", "Wet"]'::jsonb, 1, 'Thing and temperature quality.'),
  ('funbrain', 'verbal', '{"text": "Plural of CHILD?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Childes", "Children", "Childrens", "Childs"]'::jsonb, 1, 'Irregular plural.'),
  ('funbrain', 'verbal', '{"text": "Plural of MOUSE (animal)?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Mice''s", "Meeces", "Mouses", "Mice"]'::jsonb, 3, 'Irregular vowel change.'),
  ('funbrain', 'verbal', '{"text": "Plural of TOOTH?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Toothes", "Tooths", "Teeth", "Teethes"]'::jsonb, 2, 'Vowel change oo → ee.'),
  ('funbrain', 'verbal', '{"text": "Plural of WOMAN?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Women", "Womens", "Woman", "Womans"]'::jsonb, 0, 'Spelling and vowel change.'),
  ('funbrain', 'verbal', '{"text": "Plural of FOOT?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Feet", "Feet''s", "Feets", "Foots"]'::jsonb, 0, 'Same pattern as tooth/teeth.'),
  ('funbrain', 'verbal', '{"text": "Plural of SHEEP?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Sheepes", "Sheep", "Sheeps", "Sheep''s"]'::jsonb, 1, 'Same form singular and plural.'),
  ('funbrain', 'verbal', '{"text": "Plural of LEAF?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Leafes", "Leavs", "Leafs", "Leaves"]'::jsonb, 3, 'f → ves pattern.'),
  ('funbrain', 'verbal', '{"text": "Plural of KNIFE?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Knifes", "Knive", "Knifes''", "Knives"]'::jsonb, 3, 'fe → ves pattern.'),
  ('funbrain', 'verbal', '{"text": "Plural of GOOSE?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Geeses", "Gooses", "Geese", "Goose''s"]'::jsonb, 2, 'Vowel pattern like foot/feet.'),
  ('funbrain', 'verbal', '{"text": "Plural of PERSON (general)?", "pack": "cbse_verbal_puc100_foundational"}'::jsonb, '["Peoples", "Persons", "Persones", "People"]'::jsonb, 3, 'Standard plural; persons is formal/legal.');

COMMIT;
