import type { SavedRevisionCard } from "@/types";

/** Demo deck for /revision and dashboard Memory Recall when the learner has no saved cards. */
export const DEMO_REVISION_CARDS: SavedRevisionCard[] = [
  {
    id: "demo-1",
    type: "formula",
    frontContent: "What is Newton's 2nd Law in terms of momentum?",
    backContent: "F = dp/dt — force equals rate of change of momentum.",
    subtopicName: "Laws of Motion",
    topic: "Mechanics",
    subject: "physics",
    classLevel: 11,
    status: "new",
  },
  {
    id: "demo-2",
    type: "concept",
    frontContent: "Define Henry's Law and write its formula.",
    backContent:
      "p = KH·x — partial pressure of a gas is proportional to its mole fraction in solution.",
    subtopicName: "Solutions",
    topic: "Physical Chemistry",
    subject: "chemistry",
    classLevel: 11,
    status: "new",
  },
  {
    id: "demo-3",
    type: "formula",
    frontContent: "What is the integral of sec²x?",
    backContent: "∫sec²x dx = tan x + C",
    subtopicName: "Integration",
    topic: "Calculus",
    subject: "math",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-4",
    type: "concept",
    frontContent: "State Gauss's Law for electrostatics.",
    backContent: "∮E·dA = Q_enc/ε₀ — net flux equals enclosed charge divided by ε₀.",
    subtopicName: "Electrostatics",
    topic: "Electric Charges and Fields",
    subject: "physics",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-5",
    type: "concept",
    frontContent: "What is the Van't Hoff factor i?",
    backContent:
      "Ratio of actual particles in solution to formula units dissolved. i>1 for dissociation, i<1 for association.",
    subtopicName: "Colligative Properties",
    topic: "Solutions",
    subject: "chemistry",
    classLevel: 12,
    status: "tomorrow",
  },
  {
    id: "demo-6",
    type: "common_mistake",
    frontContent: "State the condition for differentiability at a point.",
    backContent: "LHD = RHD at that point, and the function must be continuous there.",
    subtopicName: "Continuity and Differentiability",
    topic: "Calculus",
    subject: "math",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-7",
    type: "formula",
    frontContent: "What is the SI unit of electric flux?",
    backContent: "N·m²/C (Newton metre squared per Coulomb), equivalent to V·m.",
    subtopicName: "Electrostatics",
    topic: "Electric Charges and Fields",
    subject: "physics",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-8",
    type: "concept",
    frontContent: "What are the four colligative properties?",
    backContent:
      "1. Vapour pressure lowering  2. Boiling point elevation  3. Freezing point depression  4. Osmotic pressure.",
    subtopicName: "Colligative Properties",
    topic: "Solutions",
    subject: "chemistry",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-9",
    type: "formula",
    frontContent: "What is the derivative of ln x?",
    backContent: "d/dx (ln x) = 1/x, for x > 0.",
    subtopicName: "Differentiation",
    topic: "Calculus",
    subject: "math",
    classLevel: 12,
    status: "tomorrow",
  },
  {
    id: "demo-10",
    type: "concept",
    frontContent: "What is Faraday's Law of electromagnetic induction?",
    backContent: "ε = −dΦ/dt — induced EMF equals negative rate of change of magnetic flux.",
    subtopicName: "Electromagnetic Induction",
    topic: "Magnetism",
    subject: "physics",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-11",
    type: "formula",
    frontContent: "Write the Nernst equation.",
    backContent: "E = E° − (RT/nF) ln Q. At 298K: E = E° − (0.0592/n) log Q.",
    subtopicName: "Electrochemistry",
    topic: "Redox Reactions",
    subject: "chemistry",
    classLevel: 12,
    status: "new",
  },
  {
    id: "demo-12",
    type: "formula",
    frontContent: "What is the formula for integration by parts?",
    backContent: "∫u dv = uv − ∫v du. Choose u using ILATE rule.",
    subtopicName: "Integration",
    topic: "Calculus",
    subject: "math",
    classLevel: 12,
    status: "new",
  },
];

/** @deprecated Use DEMO_REVISION_CARDS */
export const DEMO_CARDS = DEMO_REVISION_CARDS;
