/** Subset of live `rdm_config` defaults for offline wallet guide copy. */
export const DEFAULT_RDM_CONFIG = {
  referral_referrer_reward: 50,
  referral_referee_welcome: 25,
  referral_weekly_bonus_threshold: 5,
  referral_weekly_bonus_rdm: 100,
  challenge_5_win: 3,
  challenge_5_share: 2,
  challenge_50_win: 30,
  challenge_50_share: 20,
  refer_challenge_daily_rdm_cap: 50,
  play_dailydose_academic_rdm: 15,
  play_dailydose_funbrain_rdm: 10,
  play_dual_streak_7_rdm: 50,
  play_dual_streak_30_rdm: 200,
  study_streak_bonus_days: 90,
  study_streak_bonus_rdm: 500,
  subtopic_quiz_advanced_rdm: 15,
  subtopic_numerals_pack_rdm: 20,
  quiz_community_share_rdm: 5,
  numerals_community_share_rdm: 5,
  gyan_post_rdm: 5,
  gyan_comment_rdm: 5,
  gyan_upvote_rdm: 2,
  gyan_save_rdm: 3,
  free_trial_welcome_rdm: 500,
  free_trial_checklist_reward_rdm: 100,
  free_trial_daily_streak_reward_rdm: 80,
  free_trial_inactive_penalty_rdm: 50,
  free_inactive_penalty_rdm: 50,
  starter_inactive_penalty_rdm: 50,
  pro_inactive_penalty_rdm: 25,
} as const;

export type RdmConfigParams = typeof DEFAULT_RDM_CONFIG;
