/**
 * Generates SQL seed for curriculum_units, curriculum_chapters, curriculum_topics, curriculum_subtopics.
 * Run: npx tsx scripts/generate-curriculum-seed.ts
 * Output goes to supabase/migrations/20250322010000_curriculum_seed.sql
 */

import * as fs from "fs";
import * as path from "path";
import { class12PhysicsUnits } from "../data/class12PhysicsCurriculum";
import { class12MathUnits } from "../data/class12MathCurriculum";
import { class12ChemistryUnits } from "../data/class12ChemistryCurriculum";
import type { CurriculumUnit } from "../data/class12PhysicsCurriculum";

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function escArr(arr: string[]): string {
  return `ARRAY[${arr.map((a) => `'${esc(a)}'`).join(", ")}]::text[]`;
}

function generateForSubject(
  units: CurriculumUnit[],
  subject: "physics" | "math" | "chemistry",
  classLevel: number
): string[] {
  const lines: string[] = [];
  const subjectEsc = esc(subject);
  const examArr = escArr([]);

  for (let ui = 0; ui < units.length; ui++) {
    const unit = units[ui]!;
    const unitLabelEsc = esc(unit.unitLabel);
    const unitTitleEsc = esc(unit.unitTitle);
    lines.push(
      `INSERT INTO public.curriculum_units (subject, class_level, unit_label, unit_title, exam_relevance, sort_order) ` +
        `VALUES ('${subjectEsc}', ${classLevel}, '${unitLabelEsc}', '${unitTitleEsc}', ${examArr}, ${ui + 1}) ` +
        `ON CONFLICT (subject, class_level, unit_label) DO UPDATE SET unit_title = EXCLUDED.unit_title, exam_relevance = EXCLUDED.exam_relevance, sort_order = EXCLUDED.sort_order;`
    );
  }

  for (let ui = 0; ui < units.length; ui++) {
    const unit = units[ui]!;
    const unitLabelEsc = esc(unit.unitLabel);
    for (let ci = 0; ci < unit.chapters.length; ci++) {
      const ch = unit.chapters[ci]!;
      const titleEsc = esc(ch.title);
      lines.push(
        `INSERT INTO public.curriculum_chapters (unit_id, title, sort_order) ` +
          `SELECT id, '${titleEsc}', ${ci + 1} FROM public.curriculum_units ` +
          `WHERE subject='${subjectEsc}' AND class_level=${classLevel} AND unit_label='${unitLabelEsc}' LIMIT 1 ` +
          `ON CONFLICT (unit_id, title) DO UPDATE SET sort_order = EXCLUDED.sort_order;`
      );
    }
  }

  for (let ui = 0; ui < units.length; ui++) {
    const unit = units[ui]!;
    const unitLabelEsc = esc(unit.unitLabel);
    for (let ci = 0; ci < unit.chapters.length; ci++) {
      const ch = unit.chapters[ci]!;
      const chapterTitleEsc = esc(ch.title);
      for (let ti = 0; ti < ch.topics.length; ti++) {
        const topic = ch.topics[ti]!;
        const topicTitleEsc = esc(topic.title);
        lines.push(
          `INSERT INTO public.curriculum_topics (chapter_id, title, sort_order) ` +
            `SELECT c.id, '${topicTitleEsc}', ${ti + 1} FROM public.curriculum_chapters c ` +
            `JOIN public.curriculum_units u ON u.id = c.unit_id ` +
            `WHERE u.subject='${subjectEsc}' AND u.class_level=${classLevel} AND u.unit_label='${unitLabelEsc}' AND c.title='${chapterTitleEsc}' LIMIT 1 ` +
            `ON CONFLICT (chapter_id, title) DO UPDATE SET sort_order = EXCLUDED.sort_order;`
        );
      }
    }
  }

  for (let ui = 0; ui < units.length; ui++) {
    const unit = units[ui]!;
    const unitLabelEsc = esc(unit.unitLabel);
    for (let ci = 0; ci < unit.chapters.length; ci++) {
      const ch = unit.chapters[ci]!;
      const chapterTitleEsc = esc(ch.title);
      for (let ti = 0; ti < ch.topics.length; ti++) {
        const topic = ch.topics[ti]!;
        const topicTitleEsc = esc(topic.title);
        for (let si = 0; si < topic.subtopics.length; si++) {
          const sub = topic.subtopics[si]!;
          const subEsc = esc(sub);
          lines.push(
            `INSERT INTO public.curriculum_subtopics (topic_id, name, sort_order) ` +
              `SELECT t.id, '${subEsc}', ${si + 1} FROM public.curriculum_topics t ` +
              `JOIN public.curriculum_chapters c ON c.id = t.chapter_id ` +
              `JOIN public.curriculum_units u ON u.id = c.unit_id ` +
              `WHERE u.subject='${subjectEsc}' AND u.class_level=${classLevel} AND u.unit_label='${unitLabelEsc}' AND c.title='${chapterTitleEsc}' AND t.title='${topicTitleEsc}' LIMIT 1;`
          );
        }
      }
    }
  }

  return lines;
}

const physicsLines = generateForSubject(
  class12PhysicsUnits,
  "physics",
  12
);
const mathLines = generateForSubject(
  class12MathUnits,
  "math",
  12
);
const chemistryLines = generateForSubject(
  class12ChemistryUnits,
  "chemistry",
  12
);

const allLines = [
  "-- Seed Class 12 Physics, Math and Chemistry curriculum (Unit -> Chapter -> Topic -> Subtopic)",
  "-- Generated by scripts/generate-curriculum-seed.ts",
  "",
  ...physicsLines,
  "",
  ...mathLines,
  "",
  ...chemistryLines,
];

const outPath = path.join(
  __dirname,
  "..",
  "supabase",
  "migrations",
  "20250322010000_curriculum_seed.sql"
);
fs.writeFileSync(outPath, allLines.join("\n"), "utf8");
console.log("Wrote", outPath);
