from pathlib import Path

d = "div"
m = "motion.div"

lines = [
    '"use client";',
    "",
    'import { motion } from "framer-motion";',
    'import { ClipboardList } from "lucide-react";',
    'import type { PastPaper, Subject, SavedRevisionCard } from "@/types";',
    'import PrepMockSidebar from "@/components/prep-mock/PrepMockSidebar";',
    'import PrepMockStatCards from "@/components/prep-mock/PrepMockStatCards";',
    'import ClassesSection from "@/components/prep-mock/ClassesSection";',
    'import MockTestsSection from "@/components/prep-mock/MockTestsSection";',
    'import StreakCalendar from "@/components/prep-mock/StreakCalendar";',
    'import RevisionInstaCueSection from "@/components/prep-mock/RevisionInstaCueSection";',
    "",
    "export type PrepMockDashboardViewProps = {",
    "  authUserId: string;",
    "  accessToken: string | undefined;",
    "  nextClassName: string;",
    "  nextClassTime: string;",
    "  onNextClass: (info: { name: string; time: string }) => void;",
    "  calendarRefreshKey: number;",
    "  onClassCalendar: () => void;",
    "  mockPending: number;",
    "  revisionItems: number;",
    "  accuracy: number;",
    "  subjects: Subject[];",
    "  onStartMock: (subject: Subject) => void;",
    "  onViewAll: () => void;",
    "  featuredPaper: PastPaper | null;",
    "  featuredLoading?: boolean;",
    "  onStartFeaturedPaper: () => void;",
    "  revisionCards: SavedRevisionCard[];",
    "  onCalendarActivity: () => void;",
    "};",
    "",
    "export default function PrepMockDashboardView({",
    "  authUserId,",
    "  accessToken,",
    "  nextClassName,",
    "  nextClassTime,",
    "  onNextClass,",
    "  calendarRefreshKey,",
    "  onClassCalendar,",
    "  mockPending,",
    "  revisionItems,",
    "  accuracy,",
    "  subjects,",
    "  onStartMock,",
    "  onViewAll,",
    "  featuredPaper,",
    "  featuredLoading,",
    "  onStartFeaturedPaper,",
    "  revisionCards,",
    "  onCalendarActivity,",
    "}: PrepMockDashboardViewProps) {",
    "  return (",
    f"    <{m}",
    '      key="landing"',
    "      initial={{ opacity: 0 }}",
    "      animate={{ opacity: 1 }}",
    "      exit={{ opacity: 0 }}",
    '      className="flex gap-6"',
    "    >",
    "      <PrepMockSidebar />",
    "",
    f'      <{d} className="flex-1 min-w-0 space-y-8">',
    f'        <{d} className="lg:hidden">',
    "          <PrepMockSidebar />",
    f"        </{d}>",
    "",
    f'        <{d} className="flex items-center gap-3">',
    f'          <{d} className="w-10 h-10 gradient-primary rounded-xl flex items-center justify-center shrink-0">',
    '            <ClipboardList className="w-5 h-5 text-primary-foreground" />',
    f"          </{d}>",
    f"          <{d}>",
    '            <h1 className="text-xl font-display font-extrabold text-foreground">Prep + Mock</h1>',
    '            <p className="text-xs text-muted-foreground">',
    "              Classes, AI-powered scheduling, mock tests, and smart revision",
    "            </p>",
    f"          </{d}>",
    f"        </{d}>",
    "",
    "        <PrepMockStatCards",
    "          nextClassName={nextClassName}",
    "          nextClassTime={nextClassTime}",
    "          mockPending={mockPending}",
    "          revisionItems={revisionItems}",
    "          accuracy={accuracy}",
    "        />",
    "",
    f'        <{d} className="grid grid-cols-1 lg:grid-cols-2 gap-6">',
    f'          <{d} className="space-y-6">',
    "            <ClassesSection",
    "              userId={authUserId}",
    "              onNextClass={onNextClass}",
    "              accessToken={accessToken}",
    "              onClassCalendar={onClassCalendar}",
    "            />",
    f'            <{d} id="calendar" className="scroll-mt-24">',
    "              <StreakCalendar",
    "                userId={authUserId || null}",
    "                accessToken={accessToken}",
    "                refreshKey={calendarRefreshKey}",
    "              />",
    f"            </{d}>",
    f"          </{d}>",
    "",
    f'          <{d} className="space-y-6">',
    "            <MockTestsSection",
    "              subjects={subjects}",
    "              onStartMock={onStartMock}",
    "              onViewAll={onViewAll}",
    "              featuredPaper={featuredPaper}",
    "              featuredLoading={featuredLoading}",
    "              onStartFeaturedPaper={onStartFeaturedPaper}",
    "            />",
    "            <RevisionInstaCueSection",
    "              cards={revisionCards}",
    "              accessToken={accessToken}",
    "              userId={authUserId || null}",
    "              onCalendarActivity={onCalendarActivity}",
    "            />",
    f"          </{d}>",
    f"        </{d}>",
    f"      </{d}>",
    f"    </{m}>",
    "  );",
    "}",
    "",
]

Path("components/prep-mock/dashboard/PrepMockDashboardView.tsx").write_text(
    "\n".join(lines), encoding="utf-8"
)
print("ok")
