-- Seed minimal play_questions for academic and funbrain (adaptive + daily gauntlet).

INSERT INTO public.play_questions (domain, category, difficulty_rating, content, options, correct_answer_index, explanation)
VALUES
  ('academic', 'physics', 900, '{"text": "What is the SI unit of speed?"}'::jsonb, '["m/s", "km/h", "m/s²", "km/s"]'::jsonb, 0, $$Speed = distance / time; SI units are metre and second.$$),
  ('academic', 'physics', 950, '{"text": "A body moving with uniform velocity has:"}'::jsonb, '["Zero acceleration", "Constant acceleration", "Variable acceleration", "Negative acceleration"]'::jsonb, 0, $$Uniform velocity means constant velocity; acceleration is rate of change of velocity.$$),
  ('academic', 'physics', 1000, '{"text": "What is the SI unit of force?"}'::jsonb, '["Newton", "Joule", "Watt", "Pascal"]'::jsonb, 0, $$Force = mass × acceleration; SI unit is kg·m/s² = Newton.$$),
  ('academic', 'physics', 1050, '{"text": "The value of acceleration due to gravity on Earth is approximately:"}'::jsonb, '["9.8 m/s²", "6.67 m/s²", "10.8 m/s²", "8.9 m/s²"]'::jsonb, 0, $$g on Earth surface is approximately 9.8 m/s².$$),
  ('academic', 'physics', 1100, '{"text": "The SI unit of work is:"}'::jsonb, '["Joule", "Newton", "Watt", "Pascal"]'::jsonb, 0, $$Work = Force × Displacement = N·m = Joule.$$),
  ('academic', 'chemistry', 900, '{"text": "What is the chemical symbol for gold?"}'::jsonb, '["Au", "Ag", "Fe", "Cu"]'::jsonb, 0, $$Au comes from Latin aurum.$$),
  ('academic', 'chemistry', 950, '{"text": "The pH of a neutral solution at 25°C is:"}'::jsonb, '["7", "0", "14", "1"]'::jsonb, 0, $$Neutral means equal H⁺ and OH⁻; pH = 7.$$),
  ('academic', 'chemistry', 1000, '{"text": "Which gas is most abundant in Earth''s atmosphere?"}'::jsonb, '["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"]'::jsonb, 0, $$Nitrogen is about 78% of the atmosphere.$$),
  ('academic', 'chemistry', 1050, '{"text": "What type of bond is formed when electrons are shared?"}'::jsonb, '["Covalent", "Ionic", "Metallic", "Hydrogen"]'::jsonb, 0, $$Covalent bonds involve sharing of electron pairs.$$),
  ('academic', 'chemistry', 1100, '{"text": "The atomic number of carbon is:"}'::jsonb, '["6", "12", "14", "8"]'::jsonb, 0, $$Carbon has 6 protons.$$),
  ('academic', 'math', 900, '{"text": "What is 15% of 80?"}'::jsonb, '["12", "10", "15", "8"]'::jsonb, 0, $$15% of 80 = 0.15 × 80 = 12.$$),
  ('academic', 'math', 950, '{"text": "Solve for x: 2x + 4 = 10."}'::jsonb, '["3", "4", "5", "6"]'::jsonb, 0, $$2x = 6, so x = 3.$$),
  ('academic', 'math', 1000, '{"text": "What is the area of a rectangle with length 5 and width 4?"}'::jsonb, '["20", "18", "10", "9"]'::jsonb, 0, $$Area = length × width = 5 × 4 = 20.$$),
  ('academic', 'math', 1050, '{"text": "Which is the smallest prime number?"}'::jsonb, '["2", "0", "1", "3"]'::jsonb, 0, $$2 is the only even prime.$$),
  ('academic', 'math', 1100, '{"text": "Simplify: 3² + 4²."}'::jsonb, '["25", "7", "12", "49"]'::jsonb, 0, $$9 + 16 = 25.$$),
  ('academic', 'biology', 900, '{"text": "What is the powerhouse of the cell?"}'::jsonb, '["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"]'::jsonb, 0, $$Mitochondria produce ATP.$$),
  ('academic', 'biology', 950, '{"text": "DNA is a:"}'::jsonb, '["Nucleic acid", "Protein", "Carbohydrate", "Lipid"]'::jsonb, 0, $$DNA stands for deoxyribonucleic acid.$$),
  ('academic', 'biology', 1000, '{"text": "Which organ pumps blood through the body?"}'::jsonb, '["Heart", "Lungs", "Liver", "Kidney"]'::jsonb, 0, $$The heart is the circulatory pump.$$),
  ('academic', 'biology', 1050, '{"text": "Photosynthesis occurs mainly in:"}'::jsonb, '["Chloroplasts", "Mitochondria", "Nucleus", "Ribosomes"]'::jsonb, 0, $$Chloroplasts contain chlorophyll.$$),
  ('academic', 'biology', 1100, '{"text": "How many chromosomes do humans have in a somatic cell?"}'::jsonb, '["46", "23", "44", "48"]'::jsonb, 0, $$Humans have 23 pairs = 46 chromosomes.$$),
  ('academic', 'cs', 900, '{"text": "What does CPU stand for?"}'::jsonb, '["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Control Processing Unit"]'::jsonb, 0, $$CPU is the main processor.$$),
  ('academic', 'cs', 950, '{"text": "Which of these is a programming language?"}'::jsonb, '["Python", "HTML", "CSS", "HTTP"]'::jsonb, 0, $$Python is a general-purpose programming language.$$),
  ('academic', 'cs', 1000, '{"text": "What is a variable in programming?"}'::jsonb, '["A named storage for data", "A type of loop", "A function", "An operator"]'::jsonb, 0, $$Variables store values that can change.$$),
  ('academic', 'cs', 1050, '{"text": "Which structure stores elements in LIFO order?"}'::jsonb, '["Stack", "Queue", "Array", "List"]'::jsonb, 0, $$Stack is Last In First Out.$$),
  ('academic', 'cs', 1100, '{"text": "What does API stand for?"}'::jsonb, '["Application Programming Interface", "Advanced Program Input", "Automated Protocol Interface", "Application Protocol Integration"]'::jsonb, 0, $$API defines how software components interact.$$),
  ('funbrain', 'puzzles', 900, '{"text": "What number comes next: 2, 4, 6, 8, __?"}'::jsonb, '["10", "9", "12", "7"]'::jsonb, 0, $$Pattern: add 2 each time.$$),
  ('funbrain', 'puzzles', 950, '{"text": "If you have 3 apples and take 2 away, how many do you have?"}'::jsonb, '["2", "1", "3", "5"]'::jsonb, 0, $$You took 2 away, so you have 2.$$),
  ('funbrain', 'puzzles', 1000, '{"text": "What is the next letter: A, C, E, G, __?"}'::jsonb, '["I", "H", "J", "K"]'::jsonb, 0, $$Skip one letter each time (B, D, F, H...).$$),
  ('funbrain', 'puzzles', 1050, '{"text": "How many sides does a hexagon have?"}'::jsonb, '["6", "5", "7", "8"]'::jsonb, 0, $$Hexa means six.$$),
  ('funbrain', 'puzzles', 1100, '{"text": "Complete: 7 × 8 = ?"}'::jsonb, '["56", "54", "64", "48"]'::jsonb, 0, $$7 × 8 = 56.$$),
  ('funbrain', 'verbal', 900, '{"text": "Which word is a synonym for happy?"}'::jsonb, '["Joyful", "Sad", "Angry", "Tired"]'::jsonb, 0, $$Joyful means very happy.$$),
  ('funbrain', 'verbal', 950, '{"text": "What is the opposite of begin?"}'::jsonb, '["End", "Start", "Continue", "Finish"]'::jsonb, 0, $$End is the opposite of begin.$$),
  ('funbrain', 'verbal', 1000, '{"text": "Which word does not belong: dog, cat, carrot, bird?"}'::jsonb, '["Carrot", "Dog", "Cat", "Bird"]'::jsonb, 0, $$Carrot is a vegetable; others are animals.$$),
  ('funbrain', 'verbal', 1050, '{"text": "Pick the correct spelling."}'::jsonb, '["Necessary", "Necesary", "Neccesary", "Necesery"]'::jsonb, 0, $$Necessary has one c, two s.$$),
  ('funbrain', 'verbal', 1100, '{"text": "What type of word is quickly?"}'::jsonb, '["Adverb", "Adjective", "Noun", "Verb"]'::jsonb, 0, $$It describes how; adverbs often end in -ly.$$),
  ('funbrain', 'quantitative', 900, '{"text": "If 5 pencils cost 10, what does 1 cost?"}'::jsonb, '["2", "5", "10", "15"]'::jsonb, 0, $$10 ÷ 5 = 2.$$),
  ('funbrain', 'quantitative', 950, '{"text": "What is 12 × 5?"}'::jsonb, '["60", "50", "55", "65"]'::jsonb, 0, $$12 × 5 = 60.$$),
  ('funbrain', 'quantitative', 1000, '{"text": "A train travels 120 km in 2 hours. Its speed is:"}'::jsonb, '["60 km/h", "240 km/h", "40 km/h", "100 km/h"]'::jsonb, 0, $$Speed = distance ÷ time = 120 ÷ 2.$$),
  ('funbrain', 'quantitative', 1050, '{"text": "What is 20% of 150?"}'::jsonb, '["30", "25", "35", "40"]'::jsonb, 0, $$0.20 × 150 = 30.$$),
  ('funbrain', 'quantitative', 1100, '{"text": "How many minutes are in 2.5 hours?"}'::jsonb, '["150", "120", "100", "90"]'::jsonb, 0, $$2.5 × 60 = 150 minutes.$$),
  ('funbrain', 'analytical', 900, '{"text": "All cats are animals. Fluffy is a cat. Therefore:"}'::jsonb, '["Fluffy is an animal", "Fluffy is not an animal", "Some cats are not animals", "Fluffy might be a dog"]'::jsonb, 0, $$If all cats are animals and Fluffy is a cat, Fluffy is an animal.$$),
  ('funbrain', 'analytical', 950, '{"text": "If A > B and B > C, then:"}'::jsonb, '["A > C", "A < C", "A = C", "Cannot say"]'::jsonb, 0, $$Transitivity: A is greater than B and B greater than C, so A > C.$$),
  ('funbrain', 'analytical', 1000, '{"text": "What is the missing number: 1, 4, 9, 16, __?"}'::jsonb, '["25", "20", "24", "23"]'::jsonb, 0, $$Squares: 1², 2², 3², 4², 5² = 25.$$),
  ('funbrain', 'analytical', 1050, '{"text": "Tomorrow is Saturday. What was yesterday?"}'::jsonb, '["Thursday", "Friday", "Sunday", "Monday"]'::jsonb, 0, $$If tomorrow is Sat, today is Fri, yesterday is Thu.$$),
  ('funbrain', 'analytical', 1100, '{"text": "Which is the odd one out: circle, square, triangle, rectangle?"}'::jsonb, '["Circle", "Square", "Triangle", "Rectangle"]'::jsonb, 0, $$Circle has no straight edges; others are polygons.$$)
;