-- Add JSONB columns for AI-generated artifacts (InstaCue cards, Bits MCQs, Formula practice).
ALTER TABLE public.subtopic_content
  ADD COLUMN IF NOT EXISTS instacue_cards jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bits_questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS practice_formulas jsonb NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.subtopic_content.instacue_cards IS 'JSON array of {type, frontContent, backContent} flashcards generated by AI.';
COMMENT ON COLUMN public.subtopic_content.bits_questions IS 'JSON array of {question, options[], correctAnswer, solution} MCQs generated by AI.';
COMMENT ON COLUMN public.subtopic_content.practice_formulas IS 'JSON array of {name, formulaLatex, description, bitsQuestions[]} formula practice sets generated by AI.';
