-- Teacher generated test history table
-- Tracks tests generated by teachers for question depletion and history viewing

CREATE TABLE IF NOT EXISTS teacher_generated_test_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  board TEXT NOT NULL DEFAULT 'CBSE',
  class_level INTEGER NOT NULL CHECK (class_level IN (11, 12)),
  subject TEXT NOT NULL CHECK (subject IN ('physics', 'chemistry', 'math')),
  scope TEXT NOT NULL CHECK (scope IN ('Topic-wise', 'Unit-wise')),
  chapter_title TEXT,
  topic_title TEXT,
  unit_title TEXT,
  questions JSONB NOT NULL DEFAULT '[]',
  question_count INTEGER NOT NULL DEFAULT 0,
  duration_minutes INTEGER,
  generated_at TIMESTAMPTZ DEFAULT now(),
  -- Track which specific question IDs were used to prevent reuse
  used_question_ids JSONB DEFAULT '[]'
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_teacher_test_history_teacher ON teacher_generated_test_history(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_test_history_topic ON teacher_generated_test_history(teacher_id, subject, topic_title);
CREATE INDEX IF NOT EXISTS idx_teacher_test_history_generated_at ON teacher_generated_test_history(generated_at DESC);

-- RLS: Teachers can only see their own history
ALTER TABLE teacher_generated_test_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Teachers can view own history"
  ON teacher_generated_test_history
  FOR SELECT
  TO authenticated
  USING (teacher_id = auth.uid());

CREATE POLICY "Teachers can insert own history"
  ON teacher_generated_test_history
  FOR INSERT
  TO authenticated
  WITH CHECK (teacher_id = auth.uid());

CREATE POLICY "Teachers can delete own history"
  ON teacher_generated_test_history
  FOR DELETE
  TO authenticated
  USING (teacher_id = auth.uid());
